### ISSUE TITLE
Notify developers when an action has failed

### ISSUE THREAD

**Issue by scooprinder** [TempleDAO/temple#110]
We currently rely on Github actions to deploy builds of the apps to various different environments - it is not immediately obvious that a deploy has failed, unless one happens to check Github and notice it.

We should investigate the usage of Github and Discord webhooks to push notifications to a dedicated channel in the Temple Discord server to alert more devs that something has gone wrong.

Messages that should be pushed to discord:
* Deploy to pr/stage/main vercel has failed

**Comment by nichosystem** [comment]
this exists
