### ISSUE TITLE
Refactor dapp directory structure into commons/modules

### ISSUE THREAD

**Issue by zelkibuilds** [TempleDAO/temple#155]
I suggest that, after we get Core in production we take a second look at the dapp directory structure. After pivoting our UI multiple times it got pretty messy in my opinion. Given we now have a better idea on how the dapp will grow (as in we have well defined sections of dapp like: landing page, intra, core, dao game etc) I think it'd be good to move to a directory structure that better supports that: having top level directories in `src` for each of these modules.

Something like:

```
/src
    /common
        /components
        /hooks
        /types
        /utils
    /modules
        /core
            /components
            /hooks
            /types
            /utils
```

This is a rough outline of but I think it gets the idea across.

Thoughts?

**Comment by nichosystem** [comment]
With massive dapp simplification, going to hold off on this in favor of a larger cleanup task
