### ISSUE TITLE
Clear technical debt from unused contracts

### ISSUE THREAD

**Issue by scooprinder** [TempleDAO/temple#239]
As part of the work towards core, we have many contracts, components, services and provider classes/methods that are no longer required. This has resulted in some contracts being deleted as part of #152 and subsequently reinstated as part of #233. 

#233 serves as a temporary measure to ensure we keep a decent cadence towards core but does highlight the need for us to do some housecleaning afterwards. As part of this work, we need to identify exactly which contracts we no longer interact with and which dapp classes/methods we no longer need to maintain as a result.

**Comment by butlerji** [comment]
Started a cleanup of unused contracts.

PR in draft, I'm removing a small set of contracts per commit and checking all tests continue to pass.
