### ISSUE TITLE
Github action to align dapp typechain dir with the protocol dir when changes are merged

### ISSUE THREAD

**Issue by scooprinder** [TempleDAO/temple#271]
Whenever there are changes to the contracts, this can result in changes to the compiled contract factories (typechain) which subsequently need to be ported to the dapp in order to make sure the dapp is using that correct ABIs for the contract.

A github action that runs on merge to `core|stage` that checks to see if changes exist in `protocol/contracts/**` and if so, performs an rsync (or another similar process) between `protocol/typechain` and `apps/dapp/type/`. The stack script does this here https://github.com/TempleDAO/temple/blob/core/shared/stack/run.sh#L61-L64

**Comment by BoxedFruits** [comment]
I'd like to work on this!

**Comment by BoxedFruits** [comment]
wait we can just change the outputDir of typechain to **app/dapp/src/type** lol

https://github.com/TempleDAO/temple/blob/stage/protocol/hardhat.config.ts#L74

**Comment by BoxedFruits** [comment]
Ohhhh forgot about `yarn compile`. That will probably work!

The only other way I can think of at the moment to have to generate code is taking the `protocol/typechain` out of `.gitignore` but I'll give it more thought before opening a PR
