### ISSUE TITLE
Convert all BigNumber to Stax Wrapper Class

### ISSUE THREAD

**Issue by mrfujisawa** [TempleDAO/temple#426]
When we were finishing the Core work, I converted all integers to BigNumbers.  This code could probably be cleaned up a bit (where stings become big numbers etc) we should also use the wrapper class that was written in Stax so that we can safely divide/multiply between different tokens.

**Comment by MrMysteryMeat** [comment]
it would be great if someone could provide the stax wrapper class somewhere here for those of us that dont have access to stax - being held back by this

**Comment by nichosystem** [comment]
@MrMysteryMeat utils/DecimalBigNumber is the wrapper class
