### ISSUE TITLE
Fix Core Notifications

### ISSUE THREAD

**Issue by mrfujisawa** [TempleDAO/temple#459]
The Notification Provider in Core is a mess.  Generally speaking, the code and UI could be cleaned up.

Two main places for improvement:
1. The notifications are absolutely positioned and should be fixed.  If you've scrolled down the page, you wont see a notification unless you scroll up
2. The notification manager should manage showing/animating the notification itself.  Right now the Notification has a lot of complex logic and knows how to animate itself/it could be simplified.

**Comment by MrMysteryMeat** [comment]
currently working on this
