### ISSUE TITLE
Upgrade temple contracts and tests to use custom errors

### ISSUE THREAD

**Issue by princetonbishop** [TempleDAO/temple#483]
[Solidity v0.8.4](https://github.com/ethereum/solidity/releases/tag/v0.8.4) introduced a cheaper, gas-efficient way to explain transaction errors by the use of custom errors. The use of string is expensive and inflexible and increases deploy costs. 

Resolution of this issue would upgrade Temple code/test to use custom errors.

**Comment by nichosystem** [comment]
closing for now as it's been confusing for new contributors. I think it's good to have our repo match what's deployed on-chain, and we won't redeploy contracts just for the custom errors / solidity upgrade. let's use custom errors and updated solidity versions going forward though
