### ISSUE TITLE
Ascend Feedback / Bugs

### ISSUE THREAD

**Issue by 0xalecks** [TempleDAO/temple#493]
- [ ] I can't type in order left-to-right: '0.000...1'. I have to type '1', then prefix it with '0.000..'. Super minor though as no one will actually type that
- [x] Slippage with decimals causes crash after entering swap amounts
- [x] The token allowance is a hardcoded amount? 
- [ ] Can we re-render prices/graph/table when trade has completed?
- [x] Arrow in the circle to flip from Trade TEMPLE > Trade DAI?
- [x] Correct grammar in error msg "_Amount would_ unbalanced pool too much"
- [x] dariox got the BAL304 error but not the friendly one somehow? ([error](https://gist.github.com/medariox/b6f3c504e8a7d1ec1d750efbdd620c9e), [the tx](https://goerli.etherscan.io/tx/0x52e0b91386e59799f90721f1dc1ec56928d3ed0154d822372830e646b5ecda1c) returned BAL#507 SWAP_LIMIT)
- [x] Start Date / End Date - should include the actual time of day
- [x] Only show the Temple price

**Comment by temple-advocate** [comment]
- [ ] Screen goes white if you go over 18 digits after the decimal

- [ ] Brave browser screws up after every transaction and just says "Something is wrong" in the SWAP button

- [ ] Good to break out the pool TVL like balancer does e.g. show # of TEMPLE and # of DAI tokens

- [ ] Good to show Time elapsed and Time remaining in the auction (Start/End date not very informative)

- [ ] Legends for TEMPLE price and Projeccted price are hard to read

- [ ] Would be good to show current weight of the two tokens after every update/poke

- [ ] The gold dot between the two token modals doesn't have any arrow indicators. Should be more reminiscent of a double arrow

**Comment by temple-advocate** [comment]
Proposed Auction Analytics 

1. Average price paid per TEMPLE acquired
2. # of tokens sold at every X cent price range (e.g. $0.70 to $0.75)
3. Txn volume Y axis and Time X axis

**Comment by temple-advocate** [comment]
- [ ] Pool Composition Table column 2 "Weight" is showing up to 15 digts after the decimal e.g. 28.00000000004%

**Comment by nichosystem** [comment]
Vaults deprecated
