### ISSUE TITLE
Nexus launch list

### ISSUE THREAD

**Issue by marshall2112** [TempleDAO/temple#730]
**Current list as of June 1**
- [ ] Shard mint contract for the 5 enclave shards (deploy to test net and prod)
- [ ] Add shard mint contract to env config
- [ ] Update PotCollectSlide to invoke shard mint (Add function to RelicProvider)
- [ ] Upload quest/reward banner for Path of Templar quest to mypinata.cloud (myst)
- [ ] Update quest metadata with mypinata url / shard metadata 
- [x] Update Simple-oc to point to 1 of 5 quest shard claim pages
- [x] Finalize PoT quest slides design
- [x] Update quest cell to use the tooltip
- [x] Add initial versions of new collect slides for PoT quest
- [x] Add sound effect after equip
- [x] Update quest data model to point to shard ids instead of reward logo urls

**_Previous list (archived)_**

Outstanding items
- [x] Updated sound icons
- [ ] "Enter" landing page (pending design input)
- [x] Background music persistent in all of nexus
- [x] Relic mint success video (m17)
- [ ] Quest success video (m19) (later)
- [x] Update wording on forge page (Combine Shards to Transmute)
- [x] Bug: Allowance for temple is insanely big (should just be the amount)
- [x] User manual on mobile, word wrap broken 
- [x] Update copy on user manual
- [x] The MINT Transaction notification takes you to Etherscan instead of Arbiscan
- [x] "Combine Shards to Forge" text is a little hard to read sitting on top of the glowing glowing glyphs 
- [x] Hide quests (empty array in config)
- [x] Wagmi Arbitrum bug
- [x] Dynamically get price for Sacrifice
- [x] New forge background (Pending new size)
- [x] 2 new pages usermanual and partnermanual (pending input on the design and content)
- [x] Add a section to the Relic Minting page where users will have to sacrifice X $TEMPLE in order to be able to mint (pending design)
- [x] Finalize Quests and Shards list
- [x] Refactor forge page code
- [x] Remove renounce relic button
- [x] Add forge ramp
- [x] Add bag icon to relic and forge pages

Production deployment
- [x] Prod vercel env updates (VITE_ENV=production-nexus)
- [x] Confirm domain for new site (answer https://nexus.echoingwhispers.link)
- [x] Update env to support new nexus envs
- [x] Contract addresses updated (have these for test and prod now)
- [x] Chain ID to 42161 (will be the chain id in prod)

Future UX improvements
- [x] Wallet not connected state needs cleaned up
- [ ] All errors should bubble up to the UI / toast

**Comment by temple-advocate** [comment]
"Combine Shards to Forge" text copy should be changed to "Combine Shards to Transmute" 
![image](https://user-images.githubusercontent.com/92966776/220181191-5095aadf-ce14-48bc-8754-9104e964736a.png)

Uniswap button takes me to Uniswap but on ETH network (ideally should ask me to change chains on wallet)

Word wrap broken on Mobile (Metamask browser) 
![image](https://user-images.githubusercontent.com/92966776/220181153-30baee45-e8ad-4132-bcfd-ce272f7a7a4b.png)

Change TEMPLE token perms to spend up to amount of TEMPLE needed for the sacrifice not unlimited

Play this RELIC video ONLY after "Minted Relic # <integer>" notification (e.g. after a successful mint)
"m17_mastered_compressed.mp4"

Play this QUEST video after a quest has been understaken (e.g. you consent to go on the quest even if same quest or different quest it will always be this video). Right now there are no quests yet so no need to do anything.
"m19 ..... mp4"
